# Generated by Django 4.2.9 on 2024-01-17 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('51f14141-def2-4a31-91a5-27745f520a4b'), editable=False, primary_key=True, serialize=False),
        ),
    ]
